FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir confluent-kafka psycopg2-binary

COPY etl_processor.py .

CMD ["python", "-u", "etl_processor.py"]